let books = [{
    id: 1, 
    title: "Start with why",
    author: "Simon Sinek",
    price: 80.0,
    quantity: 13 
},{
    id: 2,
    title: "But how do it know",
    author: "J. Clark Scott",
    price: 59.9,
    quantity: 22 
},{ 
    id: 3,
    title: "Clean Code",
    author: "Robert Cecil Martin",
    price: 50.0,
    quantity: 5 
},{ 
    id: 4,
    title: "Zero to One",
    author: "Peter Thiel",
    price: 45.0,
    quantity: 12
    },{ 
    id: 5,
    title: "You don't know JS",
    author: "Kyle Simpson",
    price: 39.9,
    quantity: 9 
}
];